### ISSUE TITLE
while (currentPolygon.First.Value != currentPolygon.Last.Value) loops forever on the same values 

### ISSUE THREAD

**Issue by JoeHalasz** [RandomiaGaming/Unity2DPixelPerfectCollider#5] opened 2024-09-15 20:07 UTC
while (currentPolygon.First.Value != currentPolygon.Last.Value) in TraceTextureInternal loops forever. I added some debugging stuff to try and figure it out but not sure what to do from here.... it just prints currentPolygon.First.Value and currentPolygon.Last.Value and after a few normal prints turns into this 
Here13(105, 25) (9, 335)
Here13(105, 25) (9, 335)
Here13(105, 25) (9, 335)
Here13(105, 25) (9, 335)
Here13(105, 25) (9, 335)
Here13(105, 25) (9, 335)
Here13(105, 25) (9, 335)

I attached png, the only edit i made to the meta file was making it readable/writable. 
Then I put in into the scene and pressed regenerate 
![mushroom](https://github.com/user-attachments/assets/8c9a3dec-d21f-4bf7-befb-f55cc5e9c40c)

**Comment by FinlayTheBerry** [comment] 2024-09-16 04:15
Thanks for letting me know. I was able to recreate the issue on my machine and am currently working on a fix. I'll let you know once the issue is resolved.

**Comment by FinlayTheBerry** [comment] 2024-09-16 06:11
Fix for this issue is live! I will be working on fixing a few smaller glitches over the next few days but the main functionality of the script is working. Tested with the mushroom and it generated the collider without issues. Yippie

**Closed as completed by FinlayTheBerry** 2024-09-16 06:11 UTC

**Comment by JoeHalasz** [comment] 2024-09-16 06:39
thanks so much!
